/*
 * irrconfiguration.h
 *
 *  Created on: Feb 6, 2014
 *      Author: mike
 */

#ifndef IRRCONFIGURATION_H_
#define IRRCONFIGURATION_H_

#define EYE_SPACE_NORMALS
#define USE_MSAA_DIAGONAL_CENTERED_2

#if defined(USE_MSAA_SQUARE_ROTATED_4) || defined(USE_MSAA_SQUARE_CENTERED_4)
#define SAMPLE_COUNT					4
#define MSAA_CONVOLUTION_FILTER			GCM_TEXTURE_CONVOLUTION_GAUSSIAN
#elif defined(USE_MSAA_DIAGONAL_CENTERED_2)
#define SAMPLE_COUNT					2
#define MSAA_CONVOLUTION_FILTER			GCM_TEXTURE_CONVOLUTION_QUINCUNX
#else
#define SAMPLE_COUNT					1
#define MSAA_CONVOLUTION_FILTER			GCM_TEXTURE_CONVOLUTION_QUINCUNX
#endif

#endif /* IRRCONFIGURATION_H_ */
